services:
  omniparse:
    image: savatar101/omniparse:0.1
    ports:
      - "8000:8000"
    environment:
      - NVIDIA_VISIBLE_DEVICES=all
    deploy:
      resources:
        reservations:
          devices:
            - capabilities: [ "gpu" ]
