services:
  redis:
    image: redis:8.0.3
    container_name: redis_server
    command: redis-server --appendonly yes  # 只启用持久化，不设置密码
    ports:
      - "56379:6379"
    volumes:
      - ./redis:/data
      - ./logs:/var/log/redis
    healthcheck:
      test: [ "CMD", "redis-cli", "ping" ]
      interval: 30s
      timeout: 10s
      retries: 3
    restart: always
    networks:
      - redis

volumes:
  redis:

networks:
  redis:
    name: redis
    driver: bridge
