version: '3.7'

services:
  jenkins:
    image: 'jenkins/jenkins:lts'
    container_name: 'jenkins'
    restart: always
    user: root
    ports:
      - '8989:8080' # web
      - '50000:50000' # agent
    volumes:
      - './jenkins/jenkins_home:/var/jenkins_home'
      - '/var/run/docker.sock:/var/run/docker.sock'
      - '/usr/bin/docker:/usr/bin/docker'
    networks:
      - ci-network

networks:
  ci-network:
    driver: bridge
