version: '3.7'

services:
  jenkins:
    image: 'jenkins/jenkins:lts'
    container_name: 'jenkins'
    restart: always
    user: root
    environment:
      - TZ=Asia/Shanghai
      # 使用清华大学镜像源
      - JENKINS_UC=https://mirrors.tuna.tsinghua.edu.cn/jenkins/updates/update-center.json
      - JENKINS_UC_DOWNLOAD=https://mirrors.tuna.tsinghua.edu.cn/jenkins
    ports:
      - '8989:8080' # web
      - '50000:50000' # agent
    volumes:
      - './jenkins/jenkins_home:/var/jenkins_home'
      - '/var/run/docker.sock:/var/run/docker.sock'
      - '/usr/bin/docker:/usr/bin/docker'
    networks:
      - ci-network

networks:
  ci-network:
    driver: bridge
