version: '3.7'
services:
  jenkins:
    image: 'jenkins/jenkins:lts'
    container_name: 'jenkins'
    restart: always
    user: root
    environment:
      - TZ=Asia/Shanghai
      # 使用清华大学镜像源
      - JENKINS_UC=https://mirrors.tuna.tsinghua.edu.cn/jenkins/updates/update-center.json
      # 配置HTTP代理
      - HTTP_PROXY=http://172.22.220.21:1081
      - HTTPS_PROXY=http://172.22.220.21:1081
      - NO_PROXY=localhost,127.0.0.1
      # 通过JVM参数也配置代理
      - JAVA_OPTS="-Dhttp.proxyHost=172.22.220.21 -Dhttp.proxyPort=1081 -Dhttps.proxyHost=172.22.220.21 -Dhttps.proxyPort=1081 -Dhttp.nonProxyHosts=localhost|127.0.0.1"
    ports:
      - '8989:8080' # web
      - '50000:50000' # agent
    volumes:
      - './jenkins/jenkins_home:/var/jenkins_home'
      - '/var/run/docker.sock:/var/run/docker.sock'
      - '/usr/bin/docker:/usr/bin/docker'
    networks:
      - ci-network
networks:
  ci-network:
    driver: bridge