services:
  postgres:
    image: postgres:14.5
    container_name: postgres_db
    environment:
      POSTGRES_DB: postgres_db
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin123456
    volumes:
      - type: volume
        source: postgres_data
        target: /var/lib/postgresql/data
    ports:
      - "5432:5432"
    restart: always
    healthcheck:
      test:
        [
          "CMD",
          "pg_isready",
          "-h",
          "localhost",
          "-p",
          "5432"
        ]
      interval: 10s
      timeout: 5s
      retries: 5
    logging:
      driver: json-file
      options:
        max-size: "100m"
        max-file: "30"
    networks:
      - postgres_network

volumes:
  postgres_data:
    name: postgres_data

networks:
  postgres_network:
    driver: bridge
