version: '3.8'
services:
  api-testing-server:
    image: ghcr.io/linuxsuren/api-testing:master
    ports:
      - "8080:8080"
    command: server
    environment:
      - KUBERNETES_SERVICE_HOST=""
      - KUBERNETES_SERVICE_PORT=""
    restart: always

  api-testing-collector:
    image: ghcr.io/linuxsuren/api-testing:master
    ports:
      - "1234:8080"
    volumes:
      - ./data:/var/tmp  
    command: atest-collector --filter-path /api -o /var/tmp/sample.yaml
    environment:
      - KUBERNETES_SERVICE_HOST=""
      - KUBERNETES_SERVICE_PORT=""
    restart: on-failure