services:
  zentao-mysql:
    image: mysql:5.7
    container_name: zentao-mysql
    restart: always
    ports:
      - '13306:3306'
    volumes:
      - /data/zentao/db:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=admin123456
      - MYSQL_DATABASE=zentao
    networks:
      - zentao-net

  zentao:
    # image: easysoft/zentao:latest
    image: easysoft/zentao:12.3.3
    container_name: zentao
    ports:
      - '18080:80'
    volumes:
      - /data/zentao/file:/data
    depends_on:
      - zentao-mysql
    environment:
      - ZT_MYSQL_HOST=zentao-mysql
      - ZT_MYSQL_PORT=3306
      - ZT_MYSQL_USER=root
      - ZT_MYSQL_PASSWORD=admin123456
      - ZT_MYSQL_DB=zentao
      - PHP_MAX_EXECUTION_TIME=120
      - PHP_MAX_INPUT_VARS=2000
      - PHP_MEMORY_LIMIT=512M
      - PHP_POST_MAX_SIZE=128M
      - PHP_UPLOAD_MAX_FILESIZE=128M
      # - LDAP_ENABLED=false  # 内网部署不需要LDAP认证,注释掉
      # - SMTP_ENABLED=false  # 内网部署不需要SMTP发送邮件,注释掉
      # - APP_DEFAULT_PORT=80 # 内网部署使用18080端口,注释掉
      # - APP_DOMAIN=zentao.demo.com # 内网没有域名,注释掉
      # - PROTOCOL_TYPE=http  # 使用http协议,注释掉
      - IS_CONTAINER=true
      # - LINK_GIT=false  # 不集成Git,注释掉
      # - LINK_CI=false   # 不集成持续集成,注释掉
    networks:
      - zentao-net

networks:
  zentao-net:
    driver: bridge
