services:
  hoppscotch:
    image: model.vnet.com/zhongzi/hoppscotch:latest
    container_name: hoppscotch
    restart: unless-stopped
    ports:
      - '13000:3000'
      - '13100:3100'
      - '13170:3170'
    env_file:
      - .env

  postgres:
  image: postgres:14.5
  container_name: postgres_db
  environment:
    POSTGRES_DB: postgres_db
    POSTGRES_USER: admin
    POSTGRES_PASSWORD: admin123456
  volumes:
    - postgres_data:/var/lib/postgresql/data
  ports:
    - '15432:5432'
  restart: always
  healthcheck:
    test: ['CMD', 'pg_isready', '-h', 'localhost', '-p', '5432']
    interval: 10s
    timeout: 5s
    retries: 5
  logging:
    driver: json-file
    options:
      max-size: '100m'
      max-file: '30'

volumes:
  postgres_data:
