services:
  postgres:
    image: model.vnet.com/sjhl/postgres:15
    volumes:
      - ./data/postgres_data:/data/hoppscotch/postgresql/data
    environment:
      POSTGRES_DB: hoppscotch
      POSTGRES_USER: hoppscotch
      POSTGRES_PASSWORD: hoppscotch
    networks:
      - hoppscotch-network

  hoppscotch-migrate:
    image: model.vnet.com/zhongzi/hoppscotch
    env_file:
      - hoppscotch.env
    entrypoint: sh
    depends_on:
      - postgres
    networks:
      - hoppscotch-network
    volumes:
      - ./data/share_dir:/share_dir
    restart: no
    command: -c "pnpx prisma migrate deploy"

  hoppscotch:
    image: model.vnet.com/zhongzi/hoppscotch
    ports:
      - "8080:80"
    env_file:
      - ./data/hoppscotch/hoppscotch.env
    depends_on:
      hoppscotch-migrate:
        condition: service_completed_successfully
    networks:
      - hoppscotch-network
    restart: unless-stopped

  nginx:
    image: nginx:latest
    ports:
      - "443:443"
      - "80:80"
    volumes:
      - ./data/nginx/conf:/etc/nginx/conf.d
      - ./data/nginx/ssl:/etc/nginx/ssl
    depends_on:
      - hoppscotch
    networks:
      - hoppscotch-network

  hoppscotch-proxy:
    image: model.vnet.com/sjhl/proxyscotch:latest
    ports:
      - "9159:9159"
    depends_on:
      - hoppscotch
    networks:
      - hoppscotch-network

networks:
  hoppscotch-network:
    driver: bridge
    name: hoppscotch-network