version: '3'
services:
  nginx:
    image: nginx:stable-alpine3.19-slim
    container_name: nginx
    restart: always
    volumes:
      - ./html:/usr/share/nginx/html
      - ./bili.conf:/etc/nginx/nginx.conf
    network_mode: 'host'
    # ports:
    #   - '8080:8080'
