version: '3'
services:
  nginx:
    image: nginx:stable-alpine3.19-slim
    container_name: nginx
    restart: always
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    network_mode: "service:proxy"
    depends_on:
      - proxy

  proxy:
    image: alpine/socat
    container_name: proxy
    restart: always
    ports:
      - "8080:8080"  # 端口映射移到这里
    command: tcp-listen:7890,fork,reuseaddr tcp-connect:127.0.0.1:7890
    network_mode: host