version: '3'
services:
  nginx:
    image: nginx:stable-alpine3.19-slim
    container_name: nginx-frontend
    restart: always
    volumes:
      - ./html:/usr/share/nginx/html
      - ./nginx.conf:/etc/nginx/nginx.conf
    ports:
      - "8080:8080"
    networks:
      - frontend

networks:
  frontend:
    driver: bridge
