services:
  nginx:
    image: nginx:stable-alpine3.19-slim
    container_name: nginx
    restart: always
    network_mode: host  # 直接使用主机网络
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    environment:
      - http_proxy=http://127.0.0.1:7890  # 设置代理
      - https_proxy=http://127.0.0.1:7890