version: '3'
services:
  nginx:
    image: nginx:stable-alpine3.19-slim
    container_name: nginx
    restart: always
    ports:
      - '8080:8080'
    volumes:
      - ./html:/usr/share/nginx/html
      - ./test.conf:/etc/nginx/nginx.conf
#    network_mode: 'host'

