services:
  nginx:
    image: nginx:stable-alpine3.19-slim
    container_name: nginx
    restart: always
    network_mode: host
    volumes:
      - ./bili.conf:/etc/nginx/nginx.conf:ro
    environment:
      - http_proxy=http://127.0.0.1:7890
      - https_proxy=http://127.0.0.1:7890