services:
  vllm:
    image: vllm/vllm-openai:latest
    restart: always
    ports:
      - '8000:8000'
    volumes:
      - /data/dev-tools/llm/models:/models # 使用绝对路径挂载
      - ./logs:/logs
      - ./awq_config.json:/config/awq_config.json # 映射量化配置文件
    environment:
      - HUGGING_FACE_HUB_TOKEN=你的HF_TOKEN # 如果需要的话
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]
    command: >
      --model /models/deepseek-ai/DeepSeek-R1-Distill-Qwen-7B
      --host 0.0.0.0
      --port 8000
      --tensor-parallel-size 1
      --max-num-seqs 128
      --quantization-config /config/awq_config.json
      --trust-remote-code
