services:
  vllm:
    image: vllm/vllm-openai:latest
    restart: always
    ports:
      - '8000:8000'
    volumes:
      - ../models:/models # 使用绝对路径挂载
      - ./logs:/logs
    environment:
      - HUGGING_FACE_HUB_TOKEN=你的HF_TOKEN # 如果需要的话
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]
    command: >
      --model /models/deepseek-ai/DeepSeek-R1-Distill-Qwen-7B
      --host 0.0.0.0
      --port 8000
      --tensor-parallel-size 1
      --max-num-seqs 128
      --trust-remote-code
      --gpu-memory-utilization 0.90
      --max-model-len 8192
      --swap-space 4
      --disable-log-requests
      --quantization bitsandbytes
      --load-format bitsandbytes

