version: '3'
services:
  embedding:
    image: jokerwho/bge-large-api:latest
    container_name: embedding
    ports:
      - 6009:6008
    networks:
      - embedding_network
    restart: always
    # environment:
      # sk-key: "sk-123456" 实际测试这个镜像设置环境变量无效
      # sk-key: "sk-aaabbbcccdddeeefffggghhhiiijjjkkk"
    deploy:
      resources:
        limits:
          cpus: '8'
          memory: 16G
      restart_policy:
        condition: on-failure
        max_attempts: 3
    logging:
      driver: "json-file"
      options:
        max-size: "100m"
        max-file: "5"

networks:
  embedding_network:
    name: embedding_network
