version: '3.8'
services:
  wordpress:
    image: wordpress:latest
    ports:
      - '8080:80'
    environment:
      - WORDPRESS_DB_HOST=db
      - WORDPRESS_DB_USER=admin
      - WORDPRESS_DB_PASSWORD=admin123456
      - WORDPRESS_DB_NAME=wordpress
      - WORDPRESS_ADMIN_USER=admin
      - WORDPRESS_ADMIN_PASSWORD=admin123456
      - WORDPRESS_ADMIN_EMAIL=admin@example.com
    volumes:
      - wordpress_data:/var/www/html
    depends_on:
      - db
    restart: unless-stopped

  db:
    image: mysql:5.7
    environment:
      - MYSQL_DATABASE=wordpress
      - MYSQL_USER=admin
      - MYSQL_PASSWORD=admin123456
      - MYSQL_ROOT_PASSWORD=admin123456
    volumes:
      - mysql_data:/var/lib/mysql
    restart: unless-stopped

volumes:
  wordpress_data:
  mysql_data:
