version: '3.8'

services:
  redis:
    image: redis:6.2-alpine
    restart: unless-stopped
    volumes:
      - sentry-redis:/data # 持久化 Redis 数据

  postgres:
    image: postgres:13
    restart: unless-stopped
    environment:
      POSTGRES_USER: sentry # PostgreSQL 用户名
      POSTGRES_PASSWORD: admin123456 # PostgreSQL 密码，请更换为强密码
      POSTGRES_DB: sentry # 数据库名称
    volumes:
      - sentry-postgres:/var/lib/postgresql/data # 持久化 PostgreSQL 数据

  sentry:
    image: getsentry/sentry:latest
    restart: unless-stopped
    environment:
      SENTRY_SECRET_KEY: 'generate_a_secure_key_here' # Sentry 密钥，生成一个安全的密钥
      SENTRY_REDIS_HOST: redis
      SENTRY_DB_NAME: sentry
      SENTRY_DB_USER: sentry
      SENTRY_DB_PASSWORD: admin123456
      SENTRY_POSTGRES_HOST: postgres
    depends_on:
      - redis
      - postgres
    command: sentry upgrade --noinput # 自动运行 Sentry 升级

  sentry-cron:
    image: getsentry/sentry:latest
    restart: unless-stopped
    environment:
      SENTRY_SECRET_KEY: 'generate_a_secure_key_here'
      SENTRY_REDIS_HOST: redis
      SENTRY_DB_NAME: sentry
      SENTRY_DB_USER: sentry
      SENTRY_DB_PASSWORD: admin123456
      SENTRY_POSTGRES_HOST: postgres
    depends_on:
      - redis
      - postgres
    command: sentry run cron # 运行 Sentry 定时任务服务

  sentry-worker:
    image: getsentry/sentry:latest
    restart: unless-stopped
    environment:
      SENTRY_SECRET_KEY: 'generate_a_secure_key_here'
      SENTRY_REDIS_HOST: redis
      SENTRY_DB_NAME: sentry
      SENTRY_DB_USER: sentry
      SENTRY_DB_PASSWORD: admin123456
      SENTRY_POSTGRES_HOST: postgres
    depends_on:
      - redis
      - postgres
    command: sentry run worker # 运行 Sentry 工作进程服务

volumes:
  sentry-postgres: # PostgreSQL 数据卷
  sentry-redis: # Redis 数据卷
