services:
  namesrv:
    image: apache/rocketmq:5.2.0
    container_name: rmqnamesrv
    ports:
      - "9876:9876"
    command: sh mqnamesrv
    networks:
      - rocketmq

  broker:
    image: apache/rocketmq:5.2.0
    container_name: rmqbroker
    ports:
      - "10909:10909"
      - "10911:10911"
      - "10912:10912"
    environment:
      - NAMESRV_ADDR=rmqnamesrv:9876
    depends_on:
      - namesrv
    command: sh mqbroker
    networks:
      - rocketmq

  proxy:
    image: apache/rocketmq:5.2.0
    container_name: rmqproxy
    ports:
      - "8080:8080"
      - "8081:8081"
    depends_on:
      - broker
      - namesrv
    command: sh mqproxy
    networks:
      - rocketmq

networks:
  rocketmq:
    driver: bridge
