version: '3'
services:
  rancher:
    image: rancher/rancher:latest
    restart: unless-stopped
    privileged: true
    environment:
      HTTP_PROXY: "http://clash:7890"
      HTTPS_PROXY: "http://clash:7890"
      TZ: "Asia/Shanghai"
    ports:
      - 80:80
      - 443:443
    volumes:
      - ./rancher-data:/var/lib/rancher
    networks:
      - clash

networks:
  clash:
    external: true
