version: "3.7"

services:
  registry:
    image: registry:2.7.1
    container_name: registry
    restart: always
    ports:
      - "5000:5000"
    volumes:
      - ./data:/var/lib/registry
    networks:
      - registry_network
    environment:
      REGISTRY_HTTP_SECRET: "sumingcheng"
      REGISTRY_HTTP_ADDR: ":5000"
      REGISTRY_STORAGE_FILESYSTEM_ROOTDIRECTORY: "/var/lib/registry"
      REGISTRY_HTTP_HEADERS_Access-Control-Allow-Origin: '[http://172.22.220.64]'
      REGISTRY_HTTP_HEADERS_Access-Control-Allow-Methods: '[HEAD,GET,POST,OPTIONS,DELETE]'
      REGISTRY_HTTP_HEADERS_Access-Control-Allow-Credentials: '[true]'
      REGISTRY_HTTP_HEADERS_Access-Control-Allow-Headers: '[Authorization,Accept,Cache-Control]'
      REGISTRY_HTTP_HEADERS_Access-Control-Expose-Headers: '[Docker-Content-Digest]'
      REGISTRY_STORAGE_DELETE_ENABLED: 'true'

  registry_ui:
    image: jc21/registry-ui:latest
    container_name: registry-ui
    restart: always
    ports:
      - "8080:80"
    environment:
      - REGISTRY_HOST=http://172.22.220.64:5000
      - REGISTRY_SSL=true
      - REGISTRY_DOMAIN=172.22.220.64:5000
      - REGISTRY_STORAGE_DELETE_ENABLED=true
    depends_on:
      - registry
    networks:
      - registry_network

networks:
  registry_network:
    driver: bridge

volumes:
  data:
    driver: local
