version: '3.8'
services:
  cloudreve:
    image: cloudreve/cloudreve:latest
    container_name: cloudreve
    restart: unless-stopped
    ports:
      - '5212:5212'
    volumes:
      - ./cloudreve/uploads:/cloudreve/uploads
      - ./cloudreve/conf:/cloudreve/conf
      - ./cloudreve/db:/cloudreve/db
      - ./cloudreve/avatar:/cloudreve/avatar
    depends_on:
      - aria2
      - redis

  aria2:
    container_name: aria2
    image: p3terx/aria2-pro
    restart: unless-stopped
    ports:
      - '6800:6800'
    volumes:
      - ./aria2/config:/config
      - ./cloudreve/uploads:/downloads
    environment:
      - PUID=1000
      - PGID=1000
      - RPC_SECRET=your_aria2_secret
      - RPC_PORT=6800

  redis:
    container_name: redis
    image: redis:alpine
    restart: unless-stopped
    volumes:
      - ./redis:/data
