version: '3.3'

services:
  cloudreve:
    image: cloudreve/cloudreve:latest
    container_name: cloudreve
    restart: unless-stopped
    ports:
      - "5212:5212"
    volumes:
      - ./conf.ini:/cloudreve/conf.ini  # 配置文件挂载到容器内
      - ./cloudreve.db:/cloudreve/cloudreve.db  # 数据库文件挂载到容器内
      - ./uploads:/cloudreve/uploads   # 上传文件目录挂载到容器内
      - ./avatar:/cloudreve/avatar   # 头像目录挂载到容器内
    environment:
      - TZ=Asia/Shanghai  # 可选，设置时区
    user: "1000:1000"  # 运行容器时指定用户ID，确保容器对文件具有合适的权限
