services:
  redis:
    container_name: redis
    image: bitnami/redis:latest
    restart: unless-stopped
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
    volumes:
      - ./redis_data:/bitnami/redis/data  # 使用当前目录的相对路径

  cloudreve:
    container_name: cloudreve
    image: cloudreve/cloudreve:latest
    restart: unless-stopped
    ports:
      - "5212:5212"
    volumes:
      - ./data:/data  # 使用当前目录的相对路径
      - ./uploads:/cloudreve/uploads  # 使用当前目录的相对路径
      - ./conf.ini:/cloudreve/conf.ini  # 使用当前目录的相对路径
      - ./cloudreve.db:/cloudreve/cloudreve.db  # 使用当前目录的相对路径
      - ./avatar:/cloudreve/avatar  # 使用当前目录的相对路径
    depends_on:
      - aria2

  aria2:
    container_name: aria2
    image: p3terx/aria2-pro
    restart: unless-stopped
    environment:
      - RPC_SECRET=your_aria_rpc_token
      - RPC_PORT=6800
    volumes:
      - ./aria2/config:/config  # 使用当前目录的相对路径
      - ./data:/data  # 使用当前目录的相对路径

volumes:
  redis_data:
    driver: local
  temp_data:
    driver: local
