version: "3.8"
services:
  redis:
    container_name: redis
    image: bitnami/redis:latest
    restart: unless-stopped
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
    volumes:
      - /var/lib/cloudreve/redis_data:/bitnami/redis/data

  cloudreve:
    container_name: cloudreve
    image: cloudreve/cloudreve:latest
    restart: unless-stopped
    ports:
      - "5212:5212"
    volumes:
      - /var/lib/cloudreve/data:/data
      - /var/lib/cloudreve/uploads:/cloudreve/uploads
      - /var/lib/cloudreve/conf.ini:/cloudreve/conf.ini
      - /var/lib/cloudreve/cloudreve.db:/cloudreve/cloudreve.db
      - /var/lib/cloudreve/avatar:/cloudreve/avatar
    depends_on:
      - aria2

  aria2:
    container_name: aria2
    image: p3terx/aria2-pro
    restart: unless-stopped
    environment:
      - RPC_SECRET=your_aria_rpc_token
      - RPC_PORT=6800
    volumes:
      - /var/lib/cloudreve/aria2/config:/config
      - /var/lib/cloudreve/data:/data

volumes:
  redis_data:
    driver: local
  temp_data:
    driver: local
