version: '3.7'

services:
  mysql:
    image: mysql:5.7
    container_name: mysql5.7_server
    environment:
      MYSQL_ROOT_PASSWORD: admin123456
      MYSQL_DATABASE: blog
      MYSQL_USER: sumingcheng
      MYSQL_PASSWORD: admin123456
    ports:
      - '3306:3306'
    volumes:
      - mysql5.7:/var/lib/mysql
      # 如果需要自定义配置，可以取消下面这行的注释
      # - ./my.cnf:/etc/mysql/my.cnf
    healthcheck:
      test: ['CMD', 'mysqladmin', 'ping', '-h', 'localhost']
      interval: 30s
      timeout: 10s
      retries: 3
    restart: always
    networks:
      - mysql5.7

volumes:
  mysql5.7:

networks:
  mysql5.7:
    driver: bridge
