version: '3.7'

services:
  mysql:
    image: mysql:8.0.36
    container_name: mysql_server
    environment:
      MYSQL_ROOT_PASSWORD: admin123456
      MYSQL_DATABASE: demo
      MYSQL_USER: admin
      MYSQL_PASSWORD: admin123456
    ports:
      - "3306:3306"
    command: --default-authentication-plugin=mysql_native_password
    volumes:
      - mysql:/var/lib/mysql
    healthcheck:
      test: [ "CMD", "mysqladmin", "ping", "-h", "localhost" ]
      interval: 30s
      timeout: 10s
      retries: 3
    restart: always
    networks:
      - mysql

volumes:
  mysql:


networks:
  mysql:
    driver: bridge
