apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: go-sec-kill-ingress
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /$1
spec:
  rules:
    - http:
        paths:
          - path: /go-sec-kill(/|$)(.*)
            pathType: Prefix
            backend:
              service:
                name: go-sec-kill
                port:
                  number: 9999