version: '3'
services:
  m3e_api:
    image: registry.cn-hangzhou.aliyuncs.com/fastgpt_docker/m3e-large-api:latest
    container_name: m3e-api
    environment:
      TZ: Asia/Shanghai
      # sk-key: sk-123456
      sk-key: "sk-aaabbbcccdddeeefffggghhhiiijjjkkk"
    restart: always
    networks:
      - m3e-api
    ports:
      - "6200:6008"

networks:
  m3e-api:
    driver: bridge
