version: '3.3'
services:
  alist:
    image: 'xhofe/alist:latest-ffmpeg'
    container_name: alist
    volumes:
      - '/etc/alist:/opt/alist/data'
      - '/etc/alist/root:/root'
    ports:
      - '5244:5244'
    environment:
      - PUID=0
      - PGID=0
      - UMASK=022
      - TZ=Asia/Shanghai
    restart: unless-stopped
