services:
  alist:
    image: 'xhofe/alist:latest-ffmpeg'
    container_name: alist
    volumes:
      - '/etc/alist:/opt/alist/data'
      - '/mnt/c/Thunder:/mnt'
    # ports:
    #   - '5244:5244'
    network_mode: 'host'
    environment:
      - PUID=0
      - PGID=0
      - UMASK=022
      - TZ=Asia/Shanghai
    restart: unless-stopped
